In [2]:
import pandas as pd 
import numpy as np   
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv("Base Case.csv")
data

                   Case             Disc   Item    Unit        Buoy     Disc.1
0          Without Disc              NaN   Mass    Tons      113.06          -
1          Without Disc              NaN  Draft  Meters        8.02          -
2          Without Disc              NaN    VCG  Meters        6.10          -
3          Without Disc              NaN    Rxx  Meters        4.05          -
4          Without Disc              NaN    Rzz  Meters        2.65          -
5          Without Disc              NaN    VCB  Meters        5.30          -
6          Without Disc              NaN    WLA      m²   27.88 (3)          -
7          Without Disc              NaN   IxIy      m⁴  127.403(3)          -
8          Fixed at MSL  Original Set-Up   Mass    Tons      116.85          -
9          Fixed at MSL  Original Set-Up  Draft  Meters        8.00          -
10         Fixed at MSL  Original Set-Up    VCG  Meters        6.18          -
11         Fixed at MSL  Original Set-Up    Rxx  Meters        4.02          -
12         Fixed at MSL  Original Set-Up    Rzz  Meters        2.62          -
13         Fixed at MSL  Original Set-Up    VCB  Meters        5.29       0.20
14         Fixed at MSL  Original Set-Up    WLA      m²   27.88 (3)   11.9 (3)
15         Fixed at MSL  Original Set-Up   IxIy      m⁴  127.403(3)  11.362(3)
16  Fixed Above Surface  Original Set-Up   Mass    Tons      116.85          -
17  Fixed Above Surface  Original Set-Up  Draft  Meters        8.20          -
18  Fixed Above Surface  Original Set-Up    VCG  Meters        6.24          -
19  Fixed Above Surface  Original Set-Up    Rxx  Meters        4.07          -
20  Fixed Above Surface  Original Set-Up    Rzz  Meters        2.62          -
21  Fixed Above Surface  Original Set-Up    VCB  Meters        5.43          -
22  Fixed Above Surface  Original Set-Up    WLA      m²   27.88 (3)          -
23  Fixed Above Surface  Original Set-Up   IxIy      m⁴  127.403(3)          -
24        Free Floating              NaN   Mass    Tons   111.30(1)       4.50
25        Free Floating              NaN  Draft  Meters        8.02       0.39
26        Free Floating              NaN    VCG  Meters        6.04       1.21
27        Free Floating              NaN    Rxx  Meters        4.05       2.21
28        Free Floating              NaN    Rzz  Meters        2.66       1.26
29        Free Floating              NaN    VCB  Meters        5.30       0.20
30        Free Floating              NaN    WLA      m²   27.88 (3)   11.9 (3)
31        Free Floating              NaN   IxIy      m⁴   127.4 (3)  11.362(3)

In [8]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
x, y

(array([['Without Disc', nan, 'Mass', 'Tons', '113.06'],
        ['Without Disc', nan, 'Draft', 'Meters', '8.02'],
        ['Without Disc', nan, 'VCG', 'Meters', '6.10'],
        ['Without Disc', nan, 'Rxx', 'Meters', '4.05'],
        ['Without Disc', nan, 'Rzz', 'Meters', '2.65'],
        ['Without Disc', nan, 'VCB', 'Meters', '5.30'],
        ['Without Disc', nan, 'WLA', 'm²', '27.88 (3)'],
        ['Without Disc', nan, 'IxIy', 'm⁴', '127.403(3)'],
        ['Fixed at MSL', 'Original Set-Up', 'Mass', 'Tons', '116.85'],
        ['Fixed at MSL', 'Original Set-Up', 'Draft', 'Meters', '8.00'],
        ['Fixed at MSL', 'Original Set-Up', 'VCG', 'Meters', '6.18'],
        ['Fixed at MSL', 'Original Set-Up', 'Rxx', 'Meters', '4.02'],
        ['Fixed at MSL', 'Original Set-Up', 'Rzz', 'Meters', '2.62'],
        ['Fixed at MSL', 'Original Set-Up', 'VCB', 'Meters', '5.29'],
        ['Fixed at MSL', 'Original Set-Up', 'WLA', 'm²', '27.88 (3)'],
        ['Fixed at MSL', 'Original Set-Up', 'IxIy', 'm⁴', '127.403(3)'],
        ['Fixed Above Surface', 'Original Set-Up', 'Mass', 'Tons',
         '116.85'],
        ['Fixed Above Surface', 'Original Set-Up', 'Draft', 'Meters',
         '8.20'],
        ['Fixed Above Surface', 'Original Set-Up', 'VCG', 'Meters',
         '6.24'],
        ['Fixed Above Surface', 'Original Set-Up', 'Rxx', 'Meters',
         '4.07'],
        ['Fixed Above Surface', 'Original Set-Up', 'Rzz', 'Meters',
         '2.62'],
        ['Fixed Above Surface', 'Original Set-Up', 'VCB', 'Meters',
         '5.43'],
        ['Fixed Above Surface', 'Original Set-Up', 'WLA', 'm²',
         '27.88 (3)'],
        ['Fixed Above Surface', 'Original Set-Up', 'IxIy', 'm⁴',
         '127.403(3)'],
        ['Free Floating', nan, 'Mass', 'Tons', '111.30(1)'],
        ['Free Floating', nan, 'Draft', 'Meters', '8.02'],
        ['Free Floating', nan, 'VCG', 'Meters', '6.04'],
        ['Free Floating', nan, 'Rxx', 'Meters', '4.05'],
        ['Free Floating', nan, 'Rzz', 'Meters', '2.66'],
        ['Free Floating', nan, 'VCB', 'Meters', '5.30'],
        ['Free Floating', nan, 'WLA', 'm²', '27.88 (3)'],
        ['Free Floating', nan, 'IxIy', 'm⁴', '127.4 (3)']], dtype=object),
 array(['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
        '0.20', '11.9 (3)', '11.362(3)', '-', '-', '-', '-', '-', '-', '-',
        '-', '4.50', '0.39', '1.21', '2.21', '1.26', '0.20', '11.9 (3)',
        '11.362(3)'], dtype=object))

In [11]:
pd.DataFrame(x, y)

                             0                1      2       3           4
-                 Without Disc              NaN   Mass    Tons      113.06
-                 Without Disc              NaN  Draft  Meters        8.02
-                 Without Disc              NaN    VCG  Meters        6.10
-                 Without Disc              NaN    Rxx  Meters        4.05
-                 Without Disc              NaN    Rzz  Meters        2.65
-                 Without Disc              NaN    VCB  Meters        5.30
-                 Without Disc              NaN    WLA      m²   27.88 (3)
-                 Without Disc              NaN   IxIy      m⁴  127.403(3)
-                 Fixed at MSL  Original Set-Up   Mass    Tons      116.85
-                 Fixed at MSL  Original Set-Up  Draft  Meters        8.00
-                 Fixed at MSL  Original Set-Up    VCG  Meters        6.18
-                 Fixed at MSL  Original Set-Up    Rxx  Meters        4.02
-                 Fixed at MSL  Original Set-Up    Rzz  Meters        2.62
0.20              Fixed at MSL  Original Set-Up    VCB  Meters        5.29
11.9 (3)          Fixed at MSL  Original Set-Up    WLA      m²   27.88 (3)
11.362(3)         Fixed at MSL  Original Set-Up   IxIy      m⁴  127.403(3)
-          Fixed Above Surface  Original Set-Up   Mass    Tons      116.85
-          Fixed Above Surface  Original Set-Up  Draft  Meters        8.20
-          Fixed Above Surface  Original Set-Up    VCG  Meters        6.24
-          Fixed Above Surface  Original Set-Up    Rxx  Meters        4.07
-          Fixed Above Surface  Original Set-Up    Rzz  Meters        2.62
-          Fixed Above Surface  Original Set-Up    VCB  Meters        5.43
-          Fixed Above Surface  Original Set-Up    WLA      m²   27.88 (3)
-          Fixed Above Surface  Original Set-Up   IxIy      m⁴  127.403(3)
4.50             Free Floating              NaN   Mass    Tons   111.30(1)
0.39             Free Floating              NaN  Draft  Meters        8.02
1.21             Free Floating              NaN    VCG  Meters        6.04
2.21             Free Floating              NaN    Rxx  Meters        4.05
1.26             Free Floating              NaN    Rzz  Meters        2.66
0.20             Free Floating              NaN    VCB  Meters        5.30
11.9 (3)         Free Floating              NaN    WLA      m²   27.88 (3)
11.362(3)        Free Floating              NaN   IxIy      m⁴   127.4 (3)

In [18]:
# type: ignore
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

In [19]:
# type: ignore
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [21]:
pd.DataFrame(x)

      0    1    2    3                4      5       6           7
0   0.0  0.0  0.0  1.0  Original Set-Up   Mass    Tons      113.06
1   0.0  0.0  0.0  1.0  Original Set-Up  Draft  Meters        8.02
2   0.0  0.0  0.0  1.0  Original Set-Up    VCG  Meters        6.10
3   0.0  0.0  0.0  1.0  Original Set-Up    Rxx  Meters        4.05
4   0.0  0.0  0.0  1.0  Original Set-Up    Rzz  Meters        2.65
5   0.0  0.0  0.0  1.0  Original Set-Up    VCB  Meters        5.30
6   0.0  0.0  0.0  1.0  Original Set-Up    WLA      m²   27.88 (3)
7   0.0  0.0  0.0  1.0  Original Set-Up   IxIy      m⁴  127.403(3)
8   0.0  1.0  0.0  0.0  Original Set-Up   Mass    Tons      116.85
9   0.0  1.0  0.0  0.0  Original Set-Up  Draft  Meters        8.00
10  0.0  1.0  0.0  0.0  Original Set-Up    VCG  Meters        6.18
11  0.0  1.0  0.0  0.0  Original Set-Up    Rxx  Meters        4.02
12  0.0  1.0  0.0  0.0  Original Set-Up    Rzz  Meters        2.62
13  0.0  1.0  0.0  0.0  Original Set-Up    VCB  Meters        5.29
14  0.0  1.0  0.0  0.0  Original Set-Up    WLA      m²   27.88 (3)
15  0.0  1.0  0.0  0.0  Original Set-Up   IxIy      m⁴  127.403(3)
16  1.0  0.0  0.0  0.0  Original Set-Up   Mass    Tons      116.85
17  1.0  0.0  0.0  0.0  Original Set-Up  Draft  Meters        8.20
18  1.0  0.0  0.0  0.0  Original Set-Up    VCG  Meters        6.24
19  1.0  0.0  0.0  0.0  Original Set-Up    Rxx  Meters        4.07
20  1.0  0.0  0.0  0.0  Original Set-Up    Rzz  Meters        2.62
21  1.0  0.0  0.0  0.0  Original Set-Up    VCB  Meters        5.43
22  1.0  0.0  0.0  0.0  Original Set-Up    WLA      m²   27.88 (3)
23  1.0  0.0  0.0  0.0  Original Set-Up   IxIy      m⁴  127.403(3)
24  0.0  0.0  1.0  0.0  Original Set-Up   Mass    Tons   111.30(1)
25  0.0  0.0  1.0  0.0  Original Set-Up  Draft  Meters        8.02
26  0.0  0.0  1.0  0.0  Original Set-Up    VCG  Meters        6.04
27  0.0  0.0  1.0  0.0  Original Set-Up    Rxx  Meters        4.05
28  0.0  0.0  1.0  0.0  Original Set-Up    Rzz  Meters        2.66
29  0.0  0.0  1.0  0.0  Original Set-Up    VCB  Meters        5.30
30  0.0  0.0  1.0  0.0  Original Set-Up    WLA      m²   27.88 (3)
31  0.0  0.0  1.0  0.0  Original Set-Up   IxIy      m⁴   127.4 (3)

In [22]:
y

array(['-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
       '0.20', '11.9 (3)', '11.362(3)', '-', '-', '-', '-', '-', '-', '-',
       '-', '4.50', '0.39', '1.21', '2.21', '1.26', '0.20', '11.9 (3)',
       '11.362(3)'], dtype=object)

In [23]:
# type: ignore
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
y = le.fit_transform(y)
pd.DataFrame(y)

    0
0   0
1   0
2   0
3   0
4   0
5   0
6   0
7   0
8   0
9   0
10  0
11  0
12  0
13  1
14  6
15  5
16  0
17  0
18  0
19  0
20  0
21  0
22  0
23  0
24  8
25  2
26  3
27  7
28  4
29  1
30  6
31  5

In [24]:
x, y

(array([[0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'Mass', 'Tons', '113.06'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'Draft', 'Meters', '8.02'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'VCG', 'Meters', '6.10'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'Rxx', 'Meters', '4.05'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'Rzz', 'Meters', '2.65'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'VCB', 'Meters', '5.30'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'WLA', 'm²', '27.88 (3)'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'IxIy', 'm⁴',
         '127.403(3)'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'Mass', 'Tons', '116.85'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'Draft', 'Meters', '8.00'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'VCG', 'Meters', '6.18'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'Rxx', 'Meters', '4.02'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'Rzz', 'Meters', '2.62'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'VCB', 'Meters', '5.29'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'WLA', 'm²', '27.88 (3)'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'IxIy', 'm⁴',
         '127.403(3)'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'Mass', 'Tons', '116.85'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'Draft', 'Meters', '8.20'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'VCG', 'Meters', '6.24'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'Rxx', 'Meters', '4.07'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'Rzz', 'Meters', '2.62'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'VCB', 'Meters', '5.43'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'WLA', 'm²', '27.88 (3)'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'IxIy', 'm⁴',
         '127.403(3)'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'Mass', 'Tons',
         '111.30(1)'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'Draft', 'Meters', '8.02'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'VCG', 'Meters', '6.04'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'Rxx', 'Meters', '4.05'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'Rzz', 'Meters', '2.66'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'VCB', 'Meters', '5.30'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'WLA', 'm²', '27.88 (3)'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'IxIy', 'm⁴', '127.4 (3)']],
       dtype=object),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 6, 5, 0, 0, 0, 0, 0, 0,
        0, 0, 8, 2, 3, 7, 4, 1, 6, 5]))

In [25]:
# type: ignore
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [26]:
x_train, x_test, y_train, y_test

(array([[0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'VCG', 'Meters', '6.10'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'VCG', 'Meters', '6.04'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'IxIy', 'm⁴',
         '127.403(3)'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'Mass', 'Tons', '113.06'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'Rxx', 'Meters', '4.07'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'Rzz', 'Meters', '2.65'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'Rxx', 'Meters', '4.05'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'Mass', 'Tons', '116.85'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'VCG', 'Meters', '6.24'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'IxIy', 'm⁴', '127.4 (3)'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'VCB', 'Meters', '5.29'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'Rxx', 'Meters', '4.02'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'Draft', 'Meters', '8.20'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'IxIy', 'm⁴',
         '127.403(3)'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'VCG', 'Meters', '6.18'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'WLA', 'm²', '27.88 (3)'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'Mass', 'Tons',
         '111.30(1)'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'Rxx', 'Meters', '4.05'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'Draft', 'Meters', '8.02'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'Rzz', 'Meters', '2.66'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'Draft', 'Meters', '8.02'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'Mass', 'Tons', '116.85'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'VCB', 'Meters', '5.43'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'IxIy', 'm⁴',
         '127.403(3)'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'VCB', 'Meters', '5.30']],
       dtype=object),
 array([[0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'WLA', 'm²', '27.88 (3)'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'Rzz', 'Meters', '2.62'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'Rzz', 'Meters', '2.62'],
        [1.0, 0.0, 0.0, 0.0, 'Original Set-Up', 'WLA', 'm²', '27.88 (3)'],
        [0.0, 0.0, 1.0, 0.0, 'Original Set-Up', 'VCB', 'Meters', '5.30'],
        [0.0, 0.0, 0.0, 1.0, 'Original Set-Up', 'WLA', 'm²', '27.88 (3)'],
        [0.0, 1.0, 0.0, 0.0, 'Original Set-Up', 'Draft', 'Meters', '8.00']],
       dtype=object),
 array([0, 3, 5, 0, 0, 0, 0, 0, 0, 5, 1, 0, 0, 0, 0, 6, 8, 7, 2, 4, 0, 0,
        0, 0, 0]),
 array([6, 0, 0, 0, 1, 0, 0]))